### ISSUE TITLE
<font> tag is not rendered

### ISSUE THREAD

**Issue by abramovks** [meliorence/react-native-render-html#531] opened 2021-11-02 02:01 UTC
### Decision Table

- [X] My issue does not look like “The HTML attribute 'xxx' is ignored” (unless we claim support for it)
- [X] My issue does not look like “The HTML element `<yyy>` is not rendered”

### Good Faith Declaration

- [X] I have read the HELP document here: https://git.io/JBi6R
- [X] I have read the CONTRIBUTING document here: https://git.io/JJ0Pg
- [X] I have confirmed that this bug has not been reported yet

### Description

Hello.
<font> tag is not rendered
This tag was added by React Jodit editor in the administrative panel. And text didn't render in react-native.

Solved by replacing String.replaceAll('<font', '<span').replaceAll('</font', '</span')

### React Native Information

```sh
"react-native": "0.65.1"
```

### RNRH Version

"react-native-render-html": "^6.2.0"

### Tested Platforms

- [ ] Android
- [X] iOS
- [ ] Web
- [ ] MacOS
- [ ] Windows

### Reproduction Platforms

- [ ] Android
- [X] iOS
- [ ] Web
- [ ] MacOS
- [ ] Windows

### Minimal, Reproducible Example

<RenderHtml
          contentWidth={width}
          source={{
            html: "<font>Test</font>"
          }}
/>

**Comment by jsamr** [comment] 2021-11-02 10:03
@abramovks Hi @abramovks! I am going to close because this issue is a duplicate of #405.

`<font>` is an HTML4, deprecated tag. See #405 for a detailed explanation and a solution.

**Closed by jsamr** 2021-11-02 10:03 UTC
Labels: bug
