### ISSUE TITLE
Select tag is not supported

### ISSUE THREAD

**Issue by jotilohana** [meliorence/react-native-render-html#547] opened 2022-01-29 10:12 UTC
### Decision Table

- [X] My issue does not look like “The HTML attribute 'xxx' is ignored” (unless we claim support for it)
- [X] My issue does not look like “The HTML element `<yyy>` is not rendered”

### Good Faith Declaration

- [X] I have read the HELP document here: https://git.io/JBi6R
- [X] I have read the CONTRIBUTING document here: https://git.io/JJ0Pg
- [X] I have confirmed that this bug has not been reported yet

### Description

Select tag is not supported 

### React Native Information

```sh
the select tag is valid html element but its not handled by this library you must extend the default html element model for this tag ....
```

### RNRH Version

0.16.0

### Tested Platforms

- [X] Android
- [ ] iOS
- [ ] Web
- [ ] MacOS
- [ ] Windows

### Reproduction Platforms

- [ ] Android
- [ ] iOS
- [ ] Web
- [ ] MacOS
- [ ] Windows

### Minimal, Reproducible Example

https://github.com/jsdf/react-native-htmlview

**Comment by jsamr** [comment] 2022-01-29 18:22
@jotilohana Thank you for your submission! This is a bit hidden in the docs, but interactive elements are not supported _by default_, which is suggested by the feedback you reported.
![image](https://user-images.githubusercontent.com/3646758/151672753-c3e9f8dc-0663-4fc4-a787-dd0578deafcd.png)
(see https://meliorence.github.io/react-native-render-html/docs/flow/transient-render-engine#translation)

However, you can declare a model and write a custom renderer to handle those tags. See https://meliorence.github.io/react-native-render-html/docs/guides/custom-renderers

I am closing now, as this is not a bug.

**Closed by jsamr** 2022-01-29 18:22 UTC
Labels: bug, is:missing template, is:missing reproduction
