### ISSUE TITLE
How to deal with the long rendering time when the HTML string is very long

### ISSUE THREAD

**Issue by junchenjun** [meliorence/react-native-render-html#152] opened 2018-05-19 06:33 UTC
### Is this a bug report or a feature request?

feature request

### Have you read [the guidelines](https://github.com/archriss/react-native-render-html/blob/master/CONTRIBUTING.md) regarding bug report?

Yes

### Have you read [the documentation](https://github.com/archriss/react-native-render-html/blob/master/README.md) in its entirety?

Yes

### Have you made sure that your issue hasn't already been reported/solved?

Yes

Hi, I am working on a RSS reader app using this lib, and I noticed when the HTML string gets very long (which happens a lot in case of the RSS article )  it usually takes a very long time to render the next page (the article detail page, where I am using react-native-render-html to render), and I will be stuck on the current page for quite a long time.

And I want to show a loading indicator before the detail page is finished rendering, but I don't know how to do that, because there is no way to detect when the rendering is  finished.

I wonder if there is a method I can use to detect when the rendering is finished, so I can give it a loading before everything is rendered? Or someone can give me any advices of how to do this.

Thanks a lot.

**Comment by arunshejul** [comment] 2018-05-22 10:53
Any solution ?

**Comment by jaychenjun** [comment] 2018-05-25 12:45
@arunshejul 

I am parsing the HTML string in a separate component now, and set a setTimeout() inside the componentWillMount to delay the rendering for a very short time, this doesn't fix the problem, but it does provide a much better user experience.

**Comment by jm90m** [comment] 2018-06-22 20:01
My app is able to parse the HTML String, but then it completely crashes if its long. Doesn't crash on newer devices like iPhone X, but anything older, it crashes.

Going to try and see what I can do, been stuck on this for a while.

**Comment by Exilz** [comment] 2018-06-25 08:42
@jm90m how long exactly is your HTML string ? Could you share it with us so we can investigate more ? Maybe we should split up those really long strings and render the whole thing piece by piece. That would free up the memory once the previous rendering is done, hence preventing OOM crashes.

**Comment by jm90m** [comment] 2018-06-26 16:02
@Exilz thanks again for the reply

here is how I use it 
```
      <HTML
        html={parsedHtmlBody}
        imagesMaxWidth={deviceWidth - widthOffset}
        onLinkPress={handlePostLinkPress}
        staticContentMaxWidth={deviceWidth - widthOffset}
        baseFontStyle={{
          color: tinycolor(customTheme.primaryBackgroundColor).isDark()
            ? COLORS.LIGHT_TEXT_COLOR
            : COLORS.DARK_TEXT_COLOR,
          fontFamily: FONTS.PRIMARY,
        }}
        textSelectable
      />
```

**Comment by magicmiles** [comment] 2018-09-30 13:50
Same problem here > https://tangotopics.com/ pick a post or the main post. It doesn't matter which one it is. Every single one of my posts makes my app crash when I go to parse it with the lib! :-(

**Comment by hungdev** [comment] 2018-10-04 15:47
use this lib: https://github.com/huang47/nodejs-html-truncate

**Comment by Exilz** [comment] 2019-02-08 15:58
I can't reproduce this issue... I tried to stress the plugin with an HUUGE HTML string, but I can't get it to crash or something.

Here's the HTML I'm rendering : 
https://pastebin.com/Eq8PeQm5

It's perfectly smooth on both iOS and Android.

**Comment by arnotixe** [comment] 2019-04-28 16:03
I rewrote to split HTML into chunks containing no more than one image each, and put the chunks into a Flatlist. It improved performance like 100 times. But auto-chunking HTML can be not-so-predictable...

**Comment by nguyenduy2392** [comment] 2019-08-29 02:47
> I rewrote to split HTML into chunks containing no more than one image each, and put the chunks into a Flatlist. It improved performance like 100 times. But auto-chunking HTML can be not-so-predictable... (In my case, watching device memory it became clear that loading lots of images in the HTMLview was the offender)

are you have sample html ?

**Comment by arnotixe** [comment] 2019-08-30 15:28
well, I wrote a function that rewrites 
```
<img src="img.jpg">yada yada
<img src="img.jpg">yada yada
<img src="img.jpg">yada yada
<img src="img.jpg">yada yada
<img src="img.jpg">yada yada
```
into Flatlist Items:
```
fixedContent = array [
content: "  <View>
    <HTML html={  <img src="img.jpg">yada yada   }  />
  </View>",
content: " <View>
    <HTML html={  <img src="img.jpg">yada yada   }  />
  </View>"
…]
and then rendering it with:

        <FlatList
          data={fixedContent}
          renderItem={({ item }) => item.content}
        />
```
I wrote the chunker so that every piece of fixedContent would only ever contain 1 image, no more. Can't really remember if FlatList takes an object or array, but I hope you get the idea

**Comment by aaveidt** [comment] 2019-10-16 09:38
Anyone implement lazyload for component? Since it takes too long to render html string.
I need to notice user that the view is rendering.

I'm using Suspense + lazy:
`const HtmlRender = lazy(props => import('./html.js'))`

But it only works for first time, after the component is imported, it's no longer lazy and continue to block main ui thread and forces user to wait.

**Comment by jsamr** [comment] 2021-07-06 14:47
The easiest approach I know of is indeed using a **FlatList** component. That way, only a subset of the render tree is rendered at a time. Thanks to `initialNumToRender`, the content will show up in a few milliseconds. You'll find a v6-compatible implementation here:

https://github.com/jsamr/rnrh-blog/blob/90c8f43878e33d671e873d258e89eff01eb96465/web/ArticleRenderer.tsx#L16

And you can [try out the app for a live feeling here](https://expo.io/@jsamr/react-native-blog).

Closing now but feel free to comment.

**Closed by jsamr** 2021-07-06 14:47 UTC
Labels: enhancement, is:help wanted, question
