### ISSUE TITLE
Text in not highlighted when copying in iOS

### ISSUE THREAD

**Issue by bipin-sakariya** [meliorence/react-native-render-html#523] opened 2021-09-24 10:59 UTC
### Decision Table

- [X] My issue does not look like “The HTML attribute 'xxx' is ignored” (unless we claim support for it)
- [X] My issue does not look like “The HTML element `<yyy>` is not rendered”

### Good Faith Declaration

- [X] I have read the HELP document here: https://git.io/JBi6R
- [X] I have read the CONTRIBUTING document here: https://git.io/JJ0Pg
- [X] I have confirmed that this bug has not been reported yet

### Description

When i try to copy text in iOS devices text is copying but it is not highlighted. i already set textSelectable={true}.

![Screenshot 2021-09-24 at 4 10 26 PM](https://user-images.githubusercontent.com/36040972/134661763-c4d01925-b478-4681-8f64-157adeef2fc7.png)

I try to implement this library [https://github.com/Astrocoders/react-native-selectable-text#react-native-selectable-text] and used inside render-html library HTML.js file (react-native-render-html/src/HTML.js) but it is not working. when i used react-native-selectable-text library out side render-html library it is working fine. 

### React Native Information

```sh
System:
    OS: macOS 10.15.7
  Binaries:
    Node: 16.8.0
    npm: 7.21.0
  IDEs:
    Android Studio: Android Studio Arctic Fox | 2020.3.1 Patch 1
    Xcode: 12.4 (12D4e)
```

### RNRH Version

RN : 0.62.2
RNRH : ^5.0.0-alpha.2

### Tested Platforms

- [X] Android
- [X] iOS
- [ ] Web
- [ ] MacOS
- [ ] Windows

### Reproduction Platforms

- [ ] Android
- [X] iOS
- [ ] Web
- [ ] MacOS
- [ ] Windows

### Minimal, Reproducible Example

I try to implement this library [https://github.com/Astrocoders/react-native-selectable-text#react-native-selectable-text] and used inside render-html library HTML.js file (react-native-render-html/src/HTML.js) but it is not working. when i used react-native-selectable-text library out side render-html library it is working fine. 

```
<SelectableText
                    menuItems={["Copy", "Paste"]}
                    onSelection={({ eventType, content, selectionStart, selectionEnd }) => {
                        Clipboard.setString(content)
                    }}
                    TextComponent={() => <Text>Lorem ipsum dolor sit amet, consectetur
                        adipiscing elit, sed do eiusmod tempor incididunt ut labore et
                        dolore magna aliqua.Ut enim ad minim veniam, quisnostrud exercitation
                        ullamco laboris nisi ut aliquipex ea commodo consequat.</Text>
                    }
                />
```

**Comment by jsamr** [comment] 2021-09-24 16:06
@bipin-sakariya Hi, and thanks for your submission and your efforts!

A few remarks:

- Your version is outdated (it's actually an alpha!) ; also note that v5.x is unmaintained. If you want to migrate to v6, see the official guide here: https://meliorence.github.io/react-native-render-html/docs/migration-guide
- You are attempting to tamper with the source, that's not something for which we can provide support!
- I can't reproduce the issue on my device (no reproduction provided).

Unfortunately, for all the above-mentioned reasons, I can't do much about this and I am going to close this issue. You are always welcomed to ask for help in our discord channel :-)

**Closed by jsamr** 2021-09-24 16:06 UTC
Labels: bug

**Comment by ansmlc** [comment] 2022-05-06 13:01
I have the same issue.

Added  `defaultTextProps={{selectable:true}}` but that only enabled copying of the entire text, and no way to select text.

**To reproduce:** 
Use `react-native-render-html` on iOS.

**Comment by armin23615** [comment] 2023-05-08 12:10
Same issue on version 6.3.4.

**Comment by mlembke1** [comment] 2023-06-21 17:49
@jsamr , how could you close so many issues that are bringing up the same problem? I understand that you all have requirements about how an issue is brought up. But, the point of the those requirements is to weed out false positives and to present the issue clearly to you. This issue has been presented clearly that selecting text in IOS doesn't work even with `selectable: true`.

We love this package. Great work and all that. Please work on this!

**Comment by jsamr** [comment] 2023-06-21 20:31
> how could you (...) Please work on this!

I'm going to immediately push back on this kind of tone in the OS space. I hope everyone understands that an open-source contributor works voluntarily for the good of the community. Would you ask someone working in an NGO cleaning up beaches while taking a walk, "hey, how dare you ignore that! Look at this junk, please work on this!"? You are part of this OS community, you can take this piece of junk a put it in a bin, this repo is very open to PR.

>  the point of the those requirements is to weed out false positives and to present the issue clearly to you

I get to decide what the point of those requirements are, since I designed these. These requirements are set to save precious time by asking for a full reproduction.

As of this peculiar reporting, it used a third-party library; I'm not willing to investigate third-party integrations unless I find a compelling reason to do so.

Now to get to the problem at stake, and assuming this is the problem you encountered, it seems to be a bug with React Native rendering nested `Text` elements on iOS. Quick repro here: https://snack.expo.dev/@jsamr/text-fails-to-be-selectable-on-ios You are welcome to report this bug to the official RN repo: https://github.com/facebook/react-native/issues/new/choose

**Comment by mlembke1** [comment] 2023-06-21 21:14
@jsamr , I think you have some fair points. But, I don't think it was fair for you to characterize my comment and question as a having some kind of degrading tone. I specifically said we love your package and you've put in good work.

You are obviously correct that you decide what the point of those requirements are. I posted my comment to challenge your definition, given there have been many people who have brought this up. And remember, just because someone asks you how you "could close so many issues?" doesn't mean that they think your work is trash or that you have ignored them. It is was a legitimate question.

Because of your response to the question (in your last paragraph), I can now see why this issue should be closed and all related issues, because it doesn't have to do with your library! Thank you 👍 
All the best,
Mitch

**Comment by jsamr** [comment] 2023-06-21 21:32
@mlembke1 Sorry if I misinterpreted the tone and intention. Appreciate the clarification!

**Comment by jsamr** [comment] 2023-06-21 21:42
@mlembke1 

> I don't think it was fair for you to characterize my comment and question as a having some kind of degrading tone

I didn't exactly see it that way, communicating online can be hard. But definitely "How could you ... please fix it" is not IMO the best way to engage, it may sound imperative to some ears, as in "you OS contributor owe the community some work", that is what triggered my response.

**Comment by mlembke1** [comment] 2023-06-21 21:50
@jsamr you're definitely right about communicating online. 

I could have been more clear for sure. Thanks for your understanding.
