### ISSUE TITLE
provideEmbeddedHeaders not working in <img> tag

### ISSUE THREAD

**Issue by AnuDharmarajan** [meliorence/react-native-render-html#533] opened 2021-11-03 13:33 UTC
### Decision Table

- [X] My issue does not look like “The HTML attribute 'xxx' is ignored” (unless we claim support for it)
- [X] My issue does not look like “The HTML element `<yyy>` is not rendered”

### Good Faith Declaration

- [X] I have read the HELP document here: https://git.io/JBi6R
- [X] I have read the CONTRIBUTING document here: https://git.io/JJ0Pg
- [X] I have confirmed that this bug has not been reported yet

### Description

I have added Authorization in img tag it is not working.

### React Native Information

```sh
"react-native": "0.64.1",
```

### RNRH Version

I am using react-native-render-html Version 6.1.0

### Tested Platforms

- [X] Android
- [X] iOS
- [ ] Web
- [ ] MacOS
- [ ] Windows

### Reproduction Platforms

- [X] Android
- [X] iOS
- [ ] Web
- [ ] MacOS
- [ ] Windows

### Minimal, Reproducible Example

function provideEmbeddedHeaders(uri, tagName) {
    
    if (tagName === "img" && uri.startsWith("https://xxx.xxx.com")) {
    
      return {
        
        Authorization: 'Bearer ' + accessToken
       
      }
    }
  }
return( <RenderHtml
                    contentWidth={Dimensions.get('window').width - wp('10%')}
                    source={{html: '<img src="https://xxxx.xxx.xx/xxxx/xx/xxxx/xxx/xxxx/23553.png"'}}
                    scrollEnabled={false}
                    //enableCSSInlineProcessing={true}
                    baseStyle={{fontSize:normalize(13)}}
                    emSize = {normalize(13)}
                    renderersProps={renderersProps}
                    provideEmbeddedHeaders={provideEmbeddedHeaders}
                    enableCSSInlineProcessing={true}
                    //absoluteFontSizesPixelMap ={'large'}
                  />
)

**Comment by jsamr** [comment] 2021-11-03 13:39
Hi @AnuDharmarajan, and thanks for your contribution! You didn't explain how you came up to the conclusion that the headers were not passed? Do you have access to the server logs? I'll be happy to help when you provide additional information. Thanks!

**Comment by AnuDharmarajan** [comment] 2021-11-03 13:49
@jsamr Thank you for your quick replay.  I don't have access in the server. The image is in the share point and we are passing the share point token for Authorization.

**Comment by jsamr** [comment] 2021-11-03 13:54
@AnuDharmarajan Did you manage authentication successfully by other means, with postman or other HTTP utilities, so that you can assert this library is faulty? The `provideEmbeddedHeaders` prop is unit-tested, I have doubts the issue is with this library:

https://github.com/meliorence/react-native-render-html/blob/4c63e9962d225e0bf7f1db745cf9f683f9671690/packages/render-html/src/__tests__/component.render-html.test.tsx#L834-L857

**Comment by jsamr** [comment] 2021-11-03 14:05
@AnuDharmarajan Can you log in the console from the first line of your `provideEmbeddedHttpHeaders` and test if this log is  being called, and if it is, with which arguments? In the snippet you provided, the HTML string is not valid HTML.

**Comment by AnuDharmarajan** [comment] 2021-11-03 14:57
The console is called when there is a <img> . I have given a sample HTML in the snippet because I am not able to provide the correct URL in the public platform.

**Comment by jsamr** [comment] 2021-11-03 15:39
@AnuDharmarajan I am reviewing the code; will let you know.

**Comment by AnuDharmarajan** [comment] 2021-11-03 16:05
@jsamr Thank you.

**Comment by jsamr** [comment] 2021-11-03 17:13
@AnuDharmarajan Should be fixed in v6.3.0, let me know!

**Closed** 2021-11-03 17:12 UTC
Labels: bug

**Comment by manohar27** [comment] 2024-02-05 13:21
@jsamr Hey I just came across this issue when rendering images inside tables. I am using the table-plugin.

**Comment by subspacefield-or** [comment] 2024-07-11 22:07
I'm using version 6.3.4 in IOS and this still seems to be an issue. I have an html fragment like follows: <img src="https://????/documents/23981/data" alt="Logo"> and this requires a bearer token to access. I add provideEmbeddedHeaders as follows:

```
    function provideEmbeddedHeaders(uri, tagName, params) {
        console.log("provideEmbeddedHeaders: %s", uri);
        if (tagName === "img" && uri.includes("?????")) {
            const bearerString = `Bearer ${AuthConfig.getAuthToken()}`;
            return {
                Authorization: bearerString
              }
        }
    }
    <RenderHtml
        contentWidth={width}
        source={source}
        enableExperimentalBRCollapsing={true}
        provideEmbeddedHeaders={provideEmbeddedHeaders}
        debug={true}
        renderersProps={renderersProps}
    />                                

```
I verified using Postman that the image can be downloaded with the token. Let me know if there are anymore details that can be provided to track down this issue.
