### ISSUE TITLE
The line breaks are rendered with too much vertical space

### ISSUE THREAD

**Issue by varungupta85** [meliorence/react-native-render-html#516] opened 2021-08-17 06:31 UTC
### Decision Table

- [X] My issue does not look like “The HTML attribute 'xxx' is ignored” (unless we claim support for it)
- [X] My issue does not look like “The HTML element `<yyy>` is not rendered”

### Good Faith Declaration

- [X] I have read the HELP document here: https://git.io/JBi6R
- [X] I have read the CONTRIBUTING document here: https://git.io/JJ0Pg
- [X] I have confirmed that this bug has not been reported yet

### Description

The line breaks are rendered with too much vertical space. Below is the html that I am trying to render:

```
<div>asd</div>
<div><br></div>
<div>asda</div>
<div>as</div>
<div><br></div>
<div>asda</div>
<div><br></div>
<div>asd</div>
<div><br></div>
```

I have an alarm app where user can enter formatted notes for each alarm. I am using `react-native-rich-text-editor` to allow user to enter the notes. The above html is generated by the `react-native-rich-text-editor` package. Below is how it looks in the editor

![image](https://user-images.githubusercontent.com/7475133/129660377-5dd861a5-edab-45eb-be8f-48e2700bf384.png)

Below is how it looks when rendered using `react-native-render-html`. It is rendered in the "Notes" field. Notice the vertical space around the line breaks.

![image](https://user-images.githubusercontent.com/7475133/129660434-04f2a6d7-3749-46c2-89da-c4cc352ec890.png)

Below is how it is rendered on an html editor on web

![image](https://user-images.githubusercontent.com/7475133/129660649-21110ed5-eccb-487e-8993-5f7302fd7adb.png)

Below is how I am rendering the html

```
<RenderHtml
                  contentWidth={width}
                  source={{ html: props.notes }}
                  renderersProps={renderersProps}
                  enableExperimentalMarginCollapsing={true}
                />
```

It is quite evident that there is a lot empty space vertically around the the line breaks.

Is there a way to reduce this vertical spacing. I tried using custom renderer for `br` tags but I guess that is not currently supported.

### React Native Information

```sh
System:
    OS: macOS 11.0.1
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 2.79 GB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 12.16.1 - ~/.nvm/versions/node/v12.16.1/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 6.13.4 - ~/.nvm/versions/node/v12.16.1/bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: 1.10.1 - /Users/varungupta/.rvm/rubies/ruby-2.4.1/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.2, DriverKit 20.0, macOS 11.0, tvOS 14.2, watchOS 7.1
    Android SDK:
      API Levels: 21, 23, 24, 25, 26, 27, 28, 29, 30
      Build Tools: 23.0.1, 25.0.0, 26.0.1, 26.0.2, 27.0.1, 27.0.3, 28.0.3, 29.0.2, 30.0.2
      System Images: android-26 | Google APIs Intel x86 Atom, android-26 | Google Play Intel x86 Atom, android-28 | Google APIs Intel x86 Atom, android-28 | Google Play Intel x86 Atom, android-29 | Google Play Intel x86 Atom, android-30 | Google Play Intel x86 Atom, android-S | Google APIs Intel x86 Atom_64, android-S | Google Play Intel x86 Atom_64
      Android NDK: 15.2.4203891
  IDEs:
    Android Studio: 2020.3 AI-203.7717.56.2031.7583922
    Xcode: 12.2/12B45b - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_144 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: Not Found
    react-native: 0.64.0 => 0.64.0
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

### RNRH Version

6.0.5

### Tested Platforms

- [ ] Android
- [X] iOS
- [ ] Web
- [ ] MacOS
- [ ] Windows

### Reproduction Platforms

- [ ] Android
- [X] iOS
- [ ] Web
- [ ] MacOS
- [ ] Windows

### Minimal, Reproducible Example

https://snack.expo.dev/bBGR1YQPE

**Comment by jsamr** [comment] 2021-08-18 10:41
@varungupta85 Thank you for your detailed report! I'll take a look as soon as I can.

**Comment by jsamr** [comment] 2021-08-22 12:58
@varungupta85 I found out the issue. The current implementation doesn't follow [that part of the spec](https://html.spec.whatwg.org/multipage/text-level-semantics.html#the-br-element) (emphasis mine):

> If a paragraph consists of nothing but a single br element, it represents a placeholder blank line (e.g. as in a template). Such blank lines **must not be used for presentation purposes**.

My understanding is that would mean those line breaks must not be printed. I'll work on a fix.

**Comment by jsamr** [comment] 2021-08-22 14:38
## Findings

Ignore my previous comment regarding the HTML standard. The issue stems from how React Native renders an empty `Text` element inside a `View` : 

```jsx
<View style={{backgroundColor: 'yellow'}}>
  <Text></Text>
</View>
```
![image](https://user-images.githubusercontent.com/3646758/130357044-db16f329-4554-4e7d-81b3-3d9fbae4c40f.png)

Instead of an zero-height line. 

Similarly, 

```jsx
<View style={{backgroundColor: 'yellow'}}>
  <Text>{"\n"}</Text>
</View>
```
![image](https://user-images.githubusercontent.com/3646758/130357085-224cd6d5-a750-46dd-bdc8-d0a33d16adf5.png)

So **React Native always inserts an implicit line break after empty Text** which is not how `<br>` behaves.

Another test : 

```jsx
<View style={{backgroundColor: 'yellow'}}>
  <Text>First line{"\n"}</Text>
  <Text>Second line</Text>
</View>
```
![image](https://user-images.githubusercontent.com/3646758/130357203-d2804480-780c-4a4d-81ad-97ba369241a3.png)

In HTML, an equivalent 

```html
<div>
  <span>First line</span><br/>
  <span>Second line</span>
</div>
```
will not print a blank line between the first and second line. That's because `Text` children of `View` have a flex content model.

However, this works as expected:

```jsx
<View style={{backgroundColor: 'yellow'}}>
  <Text>
    <Text>First line{'\n'}</Text>
    <Text>Second line</Text>
  </Text>
</View>
```
![image](https://user-images.githubusercontent.com/3646758/130357445-650d10a4-c563-4da4-acb0-f50060c75b89.png)

## Extracted Rules

- `<br>` tags should be rendered as empty text when they close a React Native textual formatting context (e.g. when they are the last child of a `TPhrasing` node which has no `TPhrasing` ancestor). 
- empty `TText` nodes should always be ignored instead of being rendered as empty `Text` (otherwise, an implicit line break will be inserted).

## Workaround

In the meantime, you can implement a hacky workaround via custom renderer:

```
import * as React from 'react';
import {ScrollView, StyleSheet, useWindowDimensions, Text} from 'react-native';
import HTML from 'react-native-render-html';

function isBrTNode(tnode) {
  return (
    ((tnode.tagName === null && tnode.type === 'phrasing') ||
      tnode.tagName === 'br') &&
    tnode.children.every(isBrTNode)
  );
}

const renderers = {
  div: ({TDefaultRenderer, tnode, ...props}) => {
    if (tnode.children.length === 1 && isBrTNode(tnode.children[0])) {
      return <Text />;
    }
    return <TDefaultRenderer tnode={tnode} {...props} />;
  },
};

const html = `
<div>asd</div>
<div><br></div>
<div>asda</div>
<div>as</div>
<div><br></div>
<div>asda</div>
<div><br></div>
<div>asd</div>
<div><br></div>
`;

export default function App() {
  const {width: contentWidth} = useWindowDimensions();
  return (
    <ScrollView contentContainerStyle={styles.container}>
      <HTML
        defaultTextProps={{selectable: true}}
        contentWidth={contentWidth}
        source={{html}}
        renderers={renderers}
      />
    </ScrollView>
  );
}

const styles = StyleSheet.create({
  container: {
    flexGrow: 1,
  },
});

```

**Comment by claudiozam** [comment] 2021-08-22 18:15
Thanks @jsamr !!!

**Comment by jsamr** [comment] 2021-08-22 20:10
I believe this is actually a bug in React Native, I've reported it here: https://github.com/facebook/react-native/issues/32062
What I will do is provide a prop to implement the "inferred rules" that I described in the previous post for those who want to circumvent this bug. It's going to be opt-in to prevent the introduction of breaking changes.

**Comment by varungupta85** [comment] 2021-08-24 14:04
@jsamr Thanks a lot for the workaround.

**Closed** 2021-08-28 22:16 UTC
Labels: bug, bug:upstream

**Comment by jsamr** [comment] 2021-08-28 22:22
I still need to do manual tests but you can already try two new props which should fix the issue **in version 6.1.0-alpha.1**:

- `enableExperimentalGhostLinesPrevention`
- `enableExperimentalBRCollapsing`

**You must set those props to true for the fix to apply.** I didn't want to introduce a behavioral change in a minor release, since that would break semver contract. So those are "opt-in" fixes prior to 7.0. The "experimental" flag stresses that the behavior introduced by those flags might evolve between minor releases. Thus those props are not "semver compliant".

To try out the latest alpha, just run

```
npm install react-native-render-html@next
```

See release notes: https://github.com/meliorence/react-native-render-html/releases/tag/v6.1.0-alpha.1

**Comment by jsamr** [comment] 2021-08-29 20:45
The fix has been tested and validated. To be clear, the issue identified in the aforementioned React Native bug was not the reason for **this** specific bug. It was this library which didn't honor the HTML spec. [I added a section in the docs which covers those two text-related issues](https://meliorence.github.io/react-native-render-html/docs/content/textual#caveats).

To sum things up, `enableExperimentalBRCollapsing` addresses this reported bug related to `<br>` tags, and `enableExperimentalGhostLinesPrevention` addresses the bug I reported in React Native issue tracker.

Those props are now available in the 6.1.0 release. Please let me know if it works for you! (a thumb is enough). Below are my visual tests:

<table>
<tr>
<th>
With <code>enableExperimentalBRCollapsing</code> (v6.1.0)
</th>
<th>
Without <code>enableExperimentalBRCollapsing</code> (v6.1.0)
</th>
</tr>

<tr>
<td>

![with-flags](https://user-images.githubusercontent.com/3646758/131245355-38648cd0-a742-4a4b-b58e-3adc65dffeb4.png)

</td>
<td>

![without-flags](https://user-images.githubusercontent.com/3646758/131245362-7ff43134-8594-4824-b2dc-bb5b02adf096.png)

</td>
</tr>
</table>

**NB**: `enableExperimentalGhostLinesPrevention` is actually the flag which addresses the aforementioned React Native bug. The BR collapsing bug was not caused by React Native, it was a miss in our integration of the HTML specs!

**Comment by DeepakSharma04** [comment] 2022-09-16 06:42
Hi @jsamr , I am facing this issue please help...!!
                      <ScrollView horizontal={true}>
                                <SafeAreaView>
                                  <RenderHtml
                                    contentWidth={width}
                                    source={{ html: item.body }}
                                    enableExperimentalMarginCollapsing={true}
                                    enableExperimentalBRCollapsing={true}
                                    enableExperimentalGhostLinesPrevention={true} />
                                </SafeAreaView>
                              </ScrollView>
![Simulator Screen Shot - iPhone 11 - 2022-09-16 at 12 07 20](https://user-images.githubusercontent.com/96714958/190573412-476d6f7a-a068-4b60-817e-8d433bfc1c9d.png)

**Comment by JunjieYangNextJS** [comment] 2024-03-05 04:21
> Hi @jsamr , I am facing this issue please help...!! First html content is good if I used this library -> react-native-htmlview
> 
> ```
>                            <HTMLView
>                             value={item.body.replace(/\n/g, '')}
>                             gesMaxWidth={Dimensions.get('window').width}
>                           />
> ```
> 
> But if I used this -> react-native-render-html , Second html content shows vertical space .
> 
> ```
>                   <ScrollView horizontal={true}>
>                             <SafeAreaView>
>                               <RenderHtml
>                                 contentWidth={width}
>                                 source={{ html: item.body }}
>                                 enableExperimentalMarginCollapsing={true}
>                                 enableExperimentalBRCollapsing={true}
>                                 enableExperimentalGhostLinesPrevention={true} />
>                             </SafeAreaView>
>                           </ScrollView>
> ```
> 
> ![Simulator Screen Shot - iPhone 11 - 2022-09-16 at 12 07 20](https://user-images.githubusercontent.com/96714958/190573412-476d6f7a-a068-4b60-817e-8d433bfc1c9d.png)

RenderHTML has default margins, just apply some styles to RenderHTML as tagStyles. Put margin: 0 to remove any default margins, then overwrite it with your own margins if you would like

**Comment by Zafarzz** [comment] 2025-04-09 12:55
by default every view has marginBottom = 14, try set `   defaultViewProps={{
        style: {
          marginBottom: 0,
        },
      }}`

**Comment by wppaing** [comment] 2025-04-10 02:47
> by default every view has marginBottom = 14, try set ` defaultViewProps={{ style: { marginBottom: 0, }, }}`

This actually works. I set both marginTop and marginBottom values. Btw marginVertial doesn't work.
