### ISSUE TITLE
Support <video> tag

### ISSUE THREAD

**Issue by Pradeet** [meliorence/react-native-render-html#137] opened 2018-04-19 13:10 UTC
### Is this a bug report or a feature request?

This is a Feature request.

Currently video tag is not supported.. if somehow in renders we get parsed children.. we can render..

### Have you read [the guidelines](https://github.com/archriss/react-native-render-html/blob/master/CONTRIBUTING.md) regarding bug report?

Yes.

### Have you read [the documentation](https://github.com/archriss/react-native-render-html/blob/master/README.md) in its entirety?

Yes

### Have you made sure that your issue hasn't already been reported/solved?

Yes

### Is the bug specific to iOS or Android? Or can it be reproduced on both platforms?

Both.

### Is the bug reproductible in a production environment (not a debug one)?

Yes.

### Have you been able to reproduce the bug in [the provided example](https://github.com/archriss/react-native-render-html/tree/master/Demo)?

Yes.

### Environment

Environment:
    React: 16.3.1
    React native: 0.55.3
    react-native-render-html: 3.9.3

### Expected Behavior

Video component should be rendered..

**Comment by jerearaujo03** [comment] 2018-07-27 21:02
+1

**Comment by RageOfJustice** [comment] 2018-11-15 12:33
HI! Ive tried to implement custom renderer with <video> tag using [react-native-video](https://github.com/react-native-community/react-native-video) library but it isn't working.
Seems like  prop `video` is omitted:
```javascript

<HTML
    containerStyle={styles.content}
    html={description}
    renderers={{
       video: ({ src }) => (
          <Video
             style={{ width: Dimensions.get('window').width - 30 }}
             source={{ uri: src }}
           />
        ),
     }}
/>

```

My workaround is to use change `video` tag with `videos` and format input html string

**Comment by Pradeet** [comment] 2018-11-21 09:11
Yeah that would work... but still a work around... we need not have to filter it out, just ignore it and pass down its children.

**Comment by Djinne** [comment] 2018-11-22 20:02
1: you need to set the height of the video! 
2: get rid of 'video' in IGNORED_TAGS in file react-native-render-html/src/HTMLUtils.js
about line 44,

**Comment by oleksii-lyhun** [comment] 2019-10-15 11:42
For render video I just remove video tag from ignoredTags list
`import Video from 'react-native-video'
import HTMLView from 'react-native-render-html'
import { IGNORED_TAGS } from 'react-native-render-html/src/HTMLUtils'
`
`<HTMLView
    html={content}
    renderers={{
      video: ({ src }) => (
        <Video source={{ uri: src }} />
      ),
    }}
    ignoredTags={IGNORED_TAGS.filter(tag => tag !== 'video')}
  />`

**Comment by Beissner** [comment] 2019-11-13 18:59
This work around doesn't seem to be working. Anyone else have better luck?

**Comment by FabrizioCaldarelli** [comment] 2019-12-13 10:53
>     ignoredTags={IGNORED_TAGS.filter(tag => tag !== 'video')}

Worked for me!

**Comment by jsamr** [comment] 2021-07-08 13:30
We are now handling feature requests in our new Canny. Closing, but [you can track and upvote this feature here.](https://native-html.canny.io/features/p/video-plugin)

**Closed by jsamr** 2021-07-08 13:30 UTC
Labels: new plugin, wontfix

**Comment by JonathanColetti** [comment] 2023-10-09 04:08
> HI! Ive tried to implement custom renderer with
> 
> ```js
> <HTML
>     containerStyle={styles.content}
>     html={description}
>     renderers={{
>        video: ({ src }) => (
>           <Video
>              style={{ width: Dimensions.get('window').width - 30 }}
>              source={{ uri: src }}
>            />
>         ),
>      }}
> />
> ```
> 
> My workaround is to use change `video` tag with `videos` and format input html string

Do you have a problem with placing multiple videos because I cannot. Check this stackoverflow post for a minimal reproduceable https://stackoverflow.com/questions/77252282/put-n-react-native-videos-inside-a-scrollview-that-renders-react-native-render-h
