### ISSUE TITLE
Unrecognized font family

### ISSUE THREAD

**Issue by ankitnasitmit** [meliorence/react-native-render-html#369] opened 2020-05-20 07:44 UTC
![Simulator Screen Shot - iPhone X - 2020-05-20 at 13 11 05](https://user-images.githubusercontent.com/54848773/82419721-65b29700-9a9c-11ea-9e09-728ee3fe585e.png)

1.Unrecognized font family 'serif'

**Comment by ankitnasitmit** [comment] 2020-05-20 08:23
https://github.com/react-native-training/react-native-fonts

**Comment by NandoMB** [comment] 2020-06-04 15:35
I'm with the same problem _**Unrecognized font family 'Arial, Helvetica, sans-serif'**_ and the case is, should I know every font that the user could use and import it to my app?

There's no way to replace an unrecognized font family for another one, like browsers do?

Thanks

**Comment by aje** [comment] 2020-06-30 08:00
why this issue is closed without any response?

**Comment by hikkary** [comment] 2020-07-16 00:30
Got the same issue. tried to de delete the node style but style the same.

**Comment by jsamr** [comment] 2020-07-16 09:24
@aje It was closed by the author! This error is probably caused by inline style. This is a known issue and we should be better at documenting the caveats; you can add font-style to the list of forbidden rules with the prop `ignoredStyles={['font-family']}`

**Comment by hikkary** [comment] 2020-07-16 12:49
I have found a fix for my issue, i had to delete the styles of any element who had the fontFamily style in it, i used alterChildren props to do so.

```js
   alterChildren={node => {
                if (node.name === 'time') {
                  if (node?.attribs?.style) {
                    delete node.attribs.style
                  }
                }
                if (node.name === 'a') {
                  if (node?.attribs?.style) {
                    delete node.attribs.style
                  }
                }
                if (node.name === 'p') {
                  if (node?.attribs?.style) {
                    delete node.attribs.style
                  }
                }
                if (node.name === 'div') {
                  delete node.attribs.style
                }
                return node.children
              }}
```
may be that's not the best solution, let me know if there is a better way.

**Comment by ankitnasitmit** [comment] 2020-07-16 16:50
Hello i was closed the bug because i saw this document. https://github.com/react-native-training/react-native-fonts

**Comment by KhimGurung** [comment] 2020-11-23 23:05
if you want to ignore the font-family,
<HTML html={htmlContent} contentWidth={ contentWidth } ignoredStyles = {['font-family']} />

**Comment by jsamr** [comment] 2020-11-26 17:54
This issue has been fixed in the Foundry release. Try it out now! See #430 for instructions.

**Closed** 2021-06-08 01:16 UTC
Labels: bug, domain:css, is:FAQ candidate

**Comment by jaydips2020** [comment] 2021-06-23 10:06
> if you want to ignore the font-family,
> `<HTML html={htmlContent} contentWidth={ contentWidth } ignoredStyles = {['font-family']} />`


Hey it's working thanks!
