### ISSUE TITLE
Support for style element

### ISSUE THREAD

**Issue by umairali332** [meliorence/react-native-render-html#381] opened 2020-07-16 04:13 UTC
Just wondering if following HTML can be rendered somehow. 

```html
<head>
<style>
.city {
  background-color: tomato;
  color: white;
  border: 2px solid black;
  margin: 20px;
  padding: 20px;
}
</style>
</head>
<div class="city">
  <h2>London</h2>
  <p>London is the capital of England.</p>
</div>
```

**Comment by jsamr** [comment] 2020-07-16 09:37
@umairali332 We should be better at documenting the scope of this library. This library is not a replacement for a WebView, and thus doesn't claim to support all the standards. Currently, there is no plan nor claim to support such thing as cascading style sheet, unfortunately. What you can do however, is provide your own custom styles associated with classes, with the `classesStyles` prop. The only thing we support is inline styles, but we are planning on a conservatory approach because there is no systematic correspondence between CSS rules and react native style rules, see all the issues caused by those mistransformations with the [`domain:css` tag](https://github.com/archriss/react-native-render-html/issues?q=is%3Aissue+is%3Aopen+label%3Adomain%3Acss+).

It is my understanding that this is a feature request rather than a bug report.

**Comment by ShivamJoker** [comment] 2021-06-28 08:09
It would be awesome if we will be able to extract the styles, convert it to native and apply it automatically.

**Comment by jsamr** [comment] 2021-07-08 13:13
Style elements will not be supported per se, because parsing requires creating a syntax tree, which requires a third party library and would most certainly add a lot of overhead.

However, I opened a feature request in our new Canny to convert CSS stylesheets to react-native-render-html compatible code. [You can upvote this feature here.](https://native-html.canny.io/features/p/a-build-tool-to-statically-transform-css-sheets-into-dynamic-styles). Closing now as feature requests are now handled in this Canny!

**Closed by jsamr** 2021-07-08 13:13 UTC
Labels: is:FAQ candidate, new feature
