### ISSUE TITLE
Whitespace handling differs from HTML significantly (no collapsing, newlines ignored)

### ISSUE THREAD

**Issue by fvsch** [meliorence/react-native-render-html#118] opened 2018-03-09 17:07 UTC
### Is this a bug report or a feature request?

Bug report. Though fixing this might change the behavior of this lib too much for users, so the solutions are probably to write documentation and/or provide an opt-in fix.

### Have you read [the guidelines](https://github.com/archriss/react-native-render-html/blob/master/CONTRIBUTING.md) regarding bug report?

Yes.

### Have you read [the documentation](https://github.com/archriss/react-native-render-html/blob/master/README.md) in its entirety?

Yes.

### Have you made sure that your issue hasn't already been reported/solved?

Yes, to the best of my abilities. :)

### Is the bug specific to iOS or Android? Or can it be reproduced on both platforms?

Both platforms.

### Is the bug reproductible in a production environment (not a debug one)?

Sorry, have not tried yet in a production build. I expect the same result though.

### Have you been able to reproduce the bug in [the provided example](https://github.com/archriss/react-native-render-html/tree/master/Demo)?

Have not tried, but the issue has a really simple setup so it shouldn’t differ.

### Environment

Environment:
- React: 16.0.0
- React native: 0.51.0
- react-native-render-html: 3.9.0

Target Platform:
- Android (7.0)
- iOS (11.2)

### Steps to Reproduce

Render this JSX:

```jsx
<HTML html={'  <div>  foo\n\nbar  baz  </div>  <div>zzz</div>  '} />
```

### Expected Behavior

I expected react-native-render-html to handle whitespace collapsing similarly to what HTML does. Replacing a rendered space character (U+0020 SPACE) with `•`, that would be:

```
foo•bar•baz
zzz
```

### Actual Behavior

react-native-render-html (3.9.0 and master) renders:

```
••foobar••baz
zzz
```

What seems to work:

1. Removing spaces outside of block tags if they only contain whitespaces
2. Removing whitespace at the end of a block tag's content

What seems broken:

1. Removing whitespace at the *beginning* of a block tag's content
2. Collapsing multiple spaces (and other whitespace characters) to a single rendered space, in the middle of text content
3. Collapsing newlines to a single space character, in the middle of text content (newlines seem to be removed altogether)

I suspect this lib is limited by React Native’s Text component and errs on the side of not manipulating text too much, only removing newlines?

If that is the case, I can think of two possible improvements:

1. Document this behavior and how HTML strings containing a lot of whitespace (which is common with some sources or JS editors) can show extra spaces before or between words.
2. If it makes sense, maybe provide an option for performing more HTML collapsing?

I’m going to implement some fixes on our side using simple regexps on our HTML. I can post what I come up with here if that’s useful. Or maybe I should do it in alterData for more fine-grained control?

**Comment by Exilz** [comment] 2018-03-12 08:28
Hi, thanks for the thorough report. I didn't notice this. I'd love it if you could take a stab at it and tell us what you come up with.
The goal of this library is to be as close as possible to what a webview would render, so if we can come up with a solution that somewhat improves this matter it would be great.

Depending on how much bloat this would add to the code, we can decide if we add it as a default behavior, or if we simply document this issue and provide an example of how to fix it.

**Comment by fvsch** [comment] 2018-03-12 20:53
This is the result I’m getting for a HTML string with lots of whitespace, first with no special processing and then with a custom `alterData` function that tries to mimic the HTML algorithm for whitespace collapsing:

<img width="361" alt="screen shot" src="https://user-images.githubusercontent.com/243601/37308333-0852c4ce-263e-11e8-8712-e6c2b2c65426.png">

The result is not as complete as what HTML does, for instance in the case of `<p><a>foo </a> , bar</p>`, web browsers will remove the space before the comma, but I’m not sure what the algorithm is and I’m not going that far.

The render part for this test:

```js
const testContent = `
a

e

<div>  foo\n\nbar  baz  </div>  <div>zzz</div>

<div>
  <div>
    <div>
      <blockquote>
        Salut<a href="#"> les copains </a> ,
        <span>comment ça va ?</span>
      </blockquote>
    </div>
  </div>
</div>

`

return (
  <View>
    <View style={borderStyle}>
      <HTML html={testContent} />
    </View>
    <View style={borderStyle}>
      <HTML html={testContent} alterData={collapseHtmlText} />
    </View>
  </View>
)
```

Where `collapseHtmlText` is a separate module (around 90 lines). I’m still working on it so I’ll test with more content before sharing.

**Comment by fvsch** [comment] 2018-03-13 12:11
@Exilz The current whitespace handling has bugs too:

```js
return <HTML html="<p>This <span>is</span> <strong>buggy</strong></p>" />
```

Shows:

```
This•isbuggy
```

You probably have a rule that a whitespace-only text node between two tag siblings can be dropped, but if the tags are both inline it should be kept (and collapsed to a single space if needed).

**Comment by fvsch** [comment] 2018-03-13 14:18
These parts in HTML.js are probably wrong:

```js
if (type === 'text') {
    if (!strippedData || !strippedData.length) {
        // This is blank, don't render an useless additional component
        return false;
    }
    // Text without tags, these can be mapped to the Text wrapper
    return {
        wrapper: 'Text',
        data: data.replace(/(\r\n|\n|\r)/gm, ''), // remove linebreaks
        attribs: attribs || {},
        parent,
        parentTag: parent && parent.name,
        tagName: name || 'rawtext'
    };
}
```

1. Whitespace-only text nodes should be dropped if between block elements, or at the start or end of a block element, but not in the middle. HTML has even more advanced handling, and some of it can be mimicked, e.g. you can check parents to see if the whitespace-only text node is the first or last child of an inline element that is itself the first or last child of a block element (which I’m doing in my solution for dropping initial or trailing whitespace).

Use case:

```
<!-- We should render a single space between the links -->
<p>
  <a href="…">foo</foo>
  <a href="…">bar</foo>
</p>
```

2. Line breaks should not be removed, but replaced with spaces (collapsing line breaks, tabs and ordinary spaces to a single space).

Use case:

```
<!-- We should render a single space between the words -->
<p>foo
bar</p>
```

**Comment by fvsch** [comment] 2018-03-13 14:28
My current solution uses this module:
https://gist.github.com/fvsch/d66282c34d48c86ec90bf5acbbff03f4

Which I’m using in alterData in this way:

```js
<HTML html={content} alterData={node => {
  const newData = collapseText(node)
  // return undefined to skip changing node text
  return newData !== node.data ? newData : undefined
}} />
```

Of course it cannot fix the two issues highlighted in the previous comment.

**Comment by fvsch** [comment] 2018-03-22 19:50
Sounds like a good plan. And if there a risk it can change rendering significantly for library users, it could be a semver-major change anyway.

**Comment by robertobrogi** [comment] 2018-03-28 10:10
Is a big problem the space between the tag :(
i tried the @fvsch solution but doesn't work... 
i have all  collapse text because arrive from server with tag

<strong>Abbiamo</strong> <em>completato</em> <span style="text-decoration: underline;">l'installazione</span>

**Comment by robertobrogi** [comment] 2018-03-28 10:59
@Draccan this is a good idea!

but work stange....

if use a constat work fine 

`const htmlContent = '<strong>Abbiamo</strong> <em>completato</em> <span style="text-decoration: underline;">l\'installazione</span> di tutto il pavimento in autobloccanti della 1a. Tappa della Smart City. Sono stati installati 188.000 m² di pavimento di alta qualità, la cui produzione proviene da SG Premoldados, installata nel nostro Polo Impresarial';

<HTML  html={this.addSpaceToHtml(htmlContent )}

                                                          //typeTag={'Text'}
                                                          //numberOfLines={2}
                                                          style={newsListStyle.descNews}
                                                    />`

if i use the dynamic content with the same structure your function doesn't work :( so strange

`<HTML  html={this.addSpaceToHtml(notice.content)}

                                                          //typeTag={'Text'}
                                                          //numberOfLines={2}
                                                          style={newsListStyle.descNews}
                                                    />`

**Comment by Draccan** [comment] 2018-03-28 11:26
@robertobrogi Al momento noi abbiamo un endpoint Firebase che ci restituisce un oggetto. Tra le proprietà di questo oggetto abbiamo "description" la quale contiene HTML. Non faccio altro che passargli il contenuto di quella proprietà.

Potresti provare a chiamare addSpaceToHtml in componentWillReceiveProps, nel costruttore o al mount e non direttamente sul componente HTML? Se non funziona così non so bene come aiutarti 🍡

**Comment by robertobrogi** [comment] 2018-03-28 13:03
@Draccan non funziona... sembra una cosa così banale... non capisco cosa non sta funzionando
indagherò

**Comment by Draccan** [comment] 2018-03-28 13:09
@robertobrogi  Magari fatti stampare l'output in console della stringa HTML risultante, è possibile che avvenga qualcosa di particolare (i tag sono tutti aperti e chiusi correttamente? c'è qualche errore nella stringa html?).

Se vuoi invia l'errore così magari provo a dare un'occhiata. Sarebbe utile anche la sorgente HTML che stai usando se possibile.

**We will publish the solution, if we find it, in english**

**Comment by robertobrogi** [comment] 2018-03-28 13:15
i make a call api and i have a news map:

RENDER:
`<ScrollView style={{marginTop: 15}}>
                        <View style={{marginBottom: 50}}>

                            {
                                map(this.state.notices, (notice, index) => {
                                    return (
                                        <HTML  html={this.addSpaceToHtml(notice.content)}
                                                          //typeTag={'Text'}
                                                          //numberOfLines={2}
                                                          style={newsListStyle.descNews}
                                                    />
                                    );
                                })
                            }
                        </View>
                    </ScrollView>`

before Your function:
`<strong>Abbiamo</strong> <em>completato</em> <span style="text-decoration: underline;">l'installazione</span> di tutto il pavimento in autobloccanti della 1a. Tappa della Smart City. Sono stati installati 188.000 m² di pavimento di alta qualità, la cui produzione proviene da SG Premoldados, installata nel nostro Polo Impresarial`

after after your function:
`<strong>Abbiamo</strong> <em>completato</em> <span style="text-decoration: underline;">l'installazione</span> di tutto il pavimento in autobloccanti della 1a. Tappa della Smart City. Sono stati installati 188.000 m² di pavimento di alta qualità, la cui produzione proviene da SG Premoldados, installata nel nostro Polo Impresarial`

maybe is the wrong regex?

**Comment by Draccan** [comment] 2018-03-28 13:31
It's not working in your example because you should have a space after "Abbiamo": 
"<strong>Abbiamo[space]</strong>"

It's strange because the addSpaceToHtml function uses the replace method of strings.

Have u correctly copied the function? 
`html = html.replace(/<[/]strong> **SPACE**/g, " **SPACE**</strong>");`
Pay attention to spaces. We are replacing all (/g) closure tags with one space after with one closure tag with a space before.

However, I use it in the app with an even more complex HTML full of things:
<img width="256" alt="schermata 2018-03-28 alle 15 28 58" src="https://user-images.githubusercontent.com/1204667/38031965-caf35a10-329c-11e8-835c-f8ba159dd426.png">

**Comment by robertobrogi** [comment] 2018-03-28 13:32
life is strange .... :)

now works! 

the problem was thew regex:

is:
html = html.replace(/<[/]strong>/g, " </strong>");

and NOT
html = html.replace(/<[/]strong> /g, " </strong>");

without **space/g work fine...

**Comment by Draccan** [comment] 2018-03-28 13:49
Ok!

I've used the space after the tag closure because of this scenario: if I have
`<strong>hello</strong><em>world</em>`
I want to show **hello**_world_
But if I have
`<strong>hello</strong> <em>world</em>`
I want to show **hello** _world_

So I don't want to have a space between strings if the 2 tags are attached. 
The one you've written (html = html.replace(/<[/]strong>/g, " ");) will remove the strong tag closure and replace it with a space.

**Comment by fvsch** [comment] 2018-03-28 20:06
For the problem where `react-native-render-html` suppresses newline characters (instead of rendering them as a space), did you try replacing your newline characters first?

```jsx
<HTML html={myHtmlContent.replace(/\r?\n/, ' ')} />
```

**Comment by tmaly1980** [comment] 2018-06-08 16:13
I noticed that the whitespace was being rendered unlike with HTML so I took a crack at filtering the content with an alterData like so:

```
  alterData (node) {
    let { data } = node
    return data.trim()
  }
```

Seems to be much better now.

**Comment by djpetenice** [comment] 2018-06-18 12:05
Anyone having issues with spaces between adjacent links? I've tried all spacing methods and all are being ignored:

<img width="282" alt="links" src="https://user-images.githubusercontent.com/37068360/41534895-27c7909e-72f8-11e8-98fc-c6f646e0c3e5.png">

**Comment by douglasjunior** [comment] 2018-07-19 16:31
@djpetenice same problem here.

If the content is (with space between `a`):
```html
<p><a href="abc">abc</a> <a href="def">def</a></p>
```

It renders (without space):
```
abcdef
```

**Comment by douglasjunior** [comment] 2018-07-20 12:09
Based on @djpetenice genius workaround, I created this function:

```js
export const fixHtmlBlockSpaces = (str = '') => {
    const fixedStr = str.replace(/(<\/[^>]+>) +(<)/gm, (substring, group1, group2) => {
        return `${group1}<span style="color: transparent">_</span>${group2}`;
    });
    return fixedStr;
};
```

Now this:

```html
<p><a href="abc">abc</a> <a href="def">def</a></p>
```

Is replaced by this:

```html
<p><a href="abc">abc</a><span style="color: transparent">_</span><a href="def">def</a></p>
```

**Comment by MSSPL-PiyaleeMaiti** [comment] 2018-09-19 07:12
@douglasjunior  Your example works for me.

**Comment by MSSPL-PiyaleeMaiti** [comment] 2018-09-19 11:09
I also getting error on emoji image. I put below content:

`hjghjg <img class="emojioneemoji" src="1f603.png"> dfdfdfdf <img title=":nerd:" class="emojioneemoji" src="1f913.png"> dfdf df df <img title=":upside_down:" class="emojioneemoji" src="1f643.png">dfdf <img title=":upside_down:" class="emojioneemoji" src="1f643.png"><img  class="emojioneemoji" src="1f609.png"> dfdf dfdf<br>df kjhjkh jh<br>djhf jkjlk<br>djhfj<br>dkhjf h<br>jjj  <img class="emojioneemoji" src="1f606.png"><img class="emojioneemoji" src="1f606.png"> dfdf dfdf<br>lkkkk <img class="emojioneemoji" src="1f606.png">`


**Expected Behaviour :**
hjghjg :smiley: dfdfdfdf :nerd_face: dfdf df df :upside_down_face:  dfdf :upside_down_face: :wink:  dfdf dfdf
df kjhjkh jh
djhf jkjlk
djhfj
dkhjf h
jjj  :laughing: :laughing:  dfdf dfdf
lkkkk :laughing: 


**Actual Behaviour :**
![htmltextrender](https://user-images.githubusercontent.com/20696057/45749816-81f89380-bc2a-11e8-989f-6ca1078c3877.png)


Plz suggest any solution.

**Comment by tclarke-scottlogic** [comment] 2018-10-24 10:30
> @Draccan yup, these tags use the same logic as the ones fvsch pointed out.
> 
> @fvsch your solution in your gist looks pretty clean. It feels like a solid improvement, even if it's obviously not matching an actual browser rendering. I'll try it out more, and figure out whether if this can be added in the codebase by default.
> I don't feel like documenting your gist and asking people to copy and paste a hundred lines into their own project just to add this feature, and I don't want to keep bloating the module with additional props either.
> 
> I'll measure the performances impact and the potential regressions (all help is welcome here !) and if everything is going smoothly, let's add it to the project. What do you think ?

Any update on this happening?

**Comment by sinxwal** [comment] 2018-10-31 10:54
> Any update on this happening?

Finally I just switched to react-native-htmlview.
thanks, anyway.

**Comment by lovecoding530** [comment] 2018-12-20 08:20
I made a function to fix the white space between tags. 
function fixSpaceInHTML(html){
    let tagWithSpaceMatch = /<([^>]+)>\s+<([^>]+)>/.exec(html);
    if(tagWithSpaceMatch){
        let tagWithSpace = tagWithSpaceMatch[0];
        let newTagWithSpace = tagWithSpace.replace(/\s/g, '') + " ";
        let newHtml = html.replace(tagWithSpace, newTagWithSpace);
        console.log({newHtml});
        return fixSpaceInHTML(newHtml);
    }else{
        console.log({html});
        return html;
    }
}
That is working fine. 
I hope it is helpful for anyone.

**Comment by MSSPL-PiyaleeMaiti** [comment] 2019-03-15 11:43
@Exilz is there any solution for image render problem?

**Comment by War777** [comment] 2019-07-29 18:27
> I did a hack by adding a span with a single character and styling it the same colour as my background.

Jajajajajaja thinking so seriously to do the same  and add a style in web to make it look similar.

**Comment by jameskennard** [comment] 2019-08-28 12:17
Are there any plans to resolve this issue any time soon? Or are workarounds the recommended solution at the moment?

Thanks

**Comment by bobjflong** [comment] 2019-12-30 16:56
One possible workaround I've found, although I can't vouch for it as I haven't tested it fully, is tricking the library into thinking that the text node is not fully whitespace. This seems to prevent the node from being collapsed. Here I add a zero-width character to whitespace data:

```javascript
  alterData: node => {
    if (node.data.match(/\s+/)) {
      return `${data}\u200C`
    }
  }
```

In the cases I've seen, this seems to stop the whitespace from being lost. However I'm not sure if there's other impact.

**Comment by lyonsv** [comment] 2020-03-09 15:03
Applying the following replace function to data before passing it to the component works for all our content so far: 

```.replace(/[\t\r\n ]+/g, ' ')```

**Comment by jsamr** [comment] 2020-07-14 21:35
I've done some research to see where those collapsing rules are specified. It appears to be the [CSS rule `white-space`](https://www.w3.org/TR/css-text-3/#preserved-white-space). The complete reference algorithm is defined in [the CSS Text Module Level 3](https://www.w3.org/TR/2020/WD-css-text-3-20200429/), sections 3 and 4.

<details>
<summary><b>Full Reference</b></summary>
<br>
<blockquote>
<h4 class="heading settled" data-level="4.1.1" id="white-space-phase-1"><span class="secno">4.1.1. </span><span class="content">Phase I: Collapsing and Transformation</span></h4>
   <p>For each inline (including anonymous inlines; see <a data-link-type="biblio" >[CSS2]</a> section <a href="https://www.w3.org/TR/CSS2/visuren.html#anonymous">9.2.2.1</a>)
      within an <a data-link-type="dfn" href="https://www.w3.org/TR/css-display-3/#inline-formatting-context" id="ref-for-inline-formatting-context">inline formatting context</a>, <a data-link-type="dfn"  id="ref-for-white-space②①">white space characters</a> are processed as follows
      prior to <a data-link-type="dfn"  id="ref-for-line-breaking-process">line breaking</a> and <a href="https://www.w3.org/TR/css-writing-modes-3/#text-direction">bidi reordering</a>,
      ignoring <dfn data-dfn-type="dfn" data-noexport id="bidi-formatting-characters">bidi formatting characters<a class="self-link" ></a></dfn> (characters with the <code>Bidi_Control</code> property <a data-link-type="biblio" 
      as if they were not there: </p>
   <ul>
    <li id="collapse"><p>If <a class="property" data-link-type="propdesc"  id="ref-for-propdef-white-space④">white-space</a> is set to <a class="css" data-link-type="maybe"  id="ref-for-valdef-white-space-normal⑤">normal</a>, <a class="css" data-link-type="maybe"  id="ref-for-valdef-white-space-nowrap②">nowrap</a>, or <a class="css" data-link-type="maybe"  id="ref-for-valdef-white-space-pre-line①">pre-line</a>, <a data-link-type="dfn"  id="ref-for-white-space②②">white space characters</a> are considered <dfn class="dfn-paneled" data-dfn-type="dfn" data-export data-lt="collapsible white space|collapsible" id="collapsible-white-space">collapsible</dfn> and are processed by performing the following steps:</p>
     <ol><li>Any sequence of collapsible <a data-link-type="dfn"  id="ref-for-spaces③">spaces</a> and <a data-link-type="dfn"  id="ref-for-tabs①">tabs</a> immediately preceding or following a <a data-link-type="dfn"  id="ref-for-segment-break④">segment break</a> is removed. 
      <li>Collapsible <a data-link-type="dfn"  id="ref-for-segment-break⑤">segment breaks</a> are transformed for
          rendering according to the <a >segment break transformation rules</a>. 
      <li>Every <a data-link-type="dfn"  id="ref-for-collapsible-white-space①">collapsible</a> <a data-link-type="dfn"  id="ref-for-tabs②">tab</a> is converted to a collapsible space (U+0020). 
      <li>Any <a data-link-type="dfn"  id="ref-for-collapsible-white-space②">collapsible</a> <a data-link-type="dfn"  id="ref-for-spaces④">space</a> immediately following another <span id="ref-for-collapsible-white-space③">collapsible</span> <span id="ref-for-spaces⑤">space</span>—even
          one outside the boundary of the inline containing that <span id="ref-for-spaces⑥">space</span>,
          provided both <span id="ref-for-spaces⑦">spaces</span> are within the same inline formatting
          context—is collapsed to have zero advance width. (It is
          invisible, but retains its <a data-link-type="dfn"  id="ref-for-soft-wrap-opportunity②">soft wrap opportunity</a>, if any.) 
     </ol>
    <li>
     <p>If <a class="property" data-link-type="propdesc"  id="ref-for-propdef-white-space⑤">white-space</a> is set to <a class="css" data-link-type="maybe"  id="ref-for-valdef-white-space-pre③">pre</a>, <a class="css" data-link-type="maybe"  id="ref-for-valdef-white-space-pre-wrap②">pre-wrap</a>, or <a class="css" data-link-type="maybe"  id="ref-for-valdef-white-space-break-spaces①">break-spaces</a>,
      any sequence of spaces is treated as a sequence of non-breaking spaces.
      However, for <span class="css" id="ref-for-valdef-white-space-pre-wrap③">pre-wrap</span>,
      a <a data-link-type="dfn"  id="ref-for-soft-wrap-opportunity③">soft wrap opportunity</a> exists at the end of a sequence of <a data-link-type="dfn"  id="ref-for-spaces⑧">spaces</a> and/or <a data-link-type="dfn"  id="ref-for-tabs③">tabs</a>,
      while for <span class="css" id="ref-for-valdef-white-space-break-spaces②">break-spaces</span>,
      a <span id="ref-for-soft-wrap-opportunity④">soft wrap opportunity</span> exists after every <span id="ref-for-spaces⑨">space</span> and every <span id="ref-for-tabs④">tab</span>. </p>
   </ul>
      <h4 class="heading settled" data-level="4.1.2" id="white-space-phase-2"><span class="secno">4.1.2. </span><span class="content">Phase II: Trimming and Positioning</span><a class="self-link" ></a></h4>
   <p>Then, the entire block is rendered.
      Inlines are laid out,
      taking <a href="https://www.w3.org/TR/css-writing-modes-3/#text-direction">bidi reordering</a> into account,
      and <a data-link-type="dfn"  id="ref-for-wrapping①">wrapping</a> as specified by the <a class="property" data-link-type="propdesc"  id="ref-for-propdef-white-space⑦">white-space</a> property.
      As each line is laid out, </p>
   <ol>
    <li>A sequence of <a data-link-type="dfn"  id="ref-for-collapsible-white-space④">collapsible</a> <a data-link-type="dfn"  id="ref-for-spaces①⑧">spaces</a> at the beginning of a line
        is removed. 
    <li>
     If the <a data-link-type="dfn"  id="ref-for-tab-size-dfn">tab size</a> is zero, <a data-link-type="dfn"  id="ref-for-preserved-white-space⑤">preserved</a> <a data-link-type="dfn"  id="ref-for-tabs⑤">tabs</a> are not rendered.
        Otherwise, each <span id="ref-for-preserved-white-space⑥">preserved</span> <span id="ref-for-tabs⑥">tab</span> is rendered as a horizontal shift
        that lines up the start edge of the next glyph with the next <a data-link-type="dfn"  id="ref-for-tab-stop">tab stop</a>.
        If this distance is less than 0.5<a href="https://www.w3.org/TR/css-values-3/#ch">ch</a>,
        then the subsequent <span id="ref-for-tab-stop①">tab stop</span> is used instead. <dfn class="dfn-paneled" data-dfn-type="dfn" data-lt="tab stop" data-noexport id="tab-stop">Tab stops</dfn> occur at points that are multiples of the <span id="ref-for-tab-size-dfn①">tab size</span> from the block’s starting content edge.
        The <span id="ref-for-tab-size-dfn②">tab size</span> is given by the <a class="property" data-link-type="propdesc"  id="ref-for-propdef-tab-size①">tab-size</a> property. 
     <p class="note" role="note"><span>Note:</span> See <a data-link-type="biblio" >[UAX9]</a> for <a href="http://unicode.org/reports/tr9/#L1">rules on how U+0009 tabulation interacts with bidi</a>.</p>
    <li>
     A sequence at the end of a line
        of <a data-link-type="dfn"  id="ref-for-collapsible-white-space⑤">collapsible</a> <a data-link-type="dfn"  id="ref-for-spaces①⑨">spaces</a> is removed,
        and any trailing U+1680 OGHAM SPACE MARK
        is also removed
        if it’s <a class="property" data-link-type="propdesc"  id="ref-for-propdef-white-space⑧">white-space</a> property is <a class="css" data-link-type="maybe"  id="ref-for-valdef-white-space-normal⑦">normal</a>, <a class="css" data-link-type="maybe"  id="ref-for-valdef-white-space-nowrap③">nowrap</a>, or <a class="css" data-link-type="maybe"  id="ref-for-valdef-white-space-pre-line②">pre-line</a>. 
     <p>In the case of bidirectional text,
        any sequence of <a data-link-type="dfn"  id="ref-for-collapsible-white-space⑥">collapsible</a> <a data-link-type="dfn"  id="ref-for-spaces②⓪">spaces</a> located at the end of the line
        prior to <a href="https://www.w3.org/TR/css-writing-modes/#text-direction">bidi reordering</a> <a data-link-type="biblio" >[CSS-WRITING-MODES-3]</a> is also removed,
        and bidi reordering is applied on the remaining content of the line.</p>
    <li>
     If there remains any sequence of <a data-link-type="dfn"  id="ref-for-white-space②③">white space</a>,
        and/or <a data-link-type="dfn"  id="ref-for-other-space-separators⑤">other space separators</a>,
        at the end of a line (after <a href="https://www.w3.org/TR/css-writing-modes/#text-direction">bidi reordering</a> <a data-link-type="biblio" >[CSS-WRITING-MODES-3]</a>): 
     <ul>
      <li>If <a class="property" data-link-type="propdesc"  id="ref-for-propdef-white-space⑨">white-space</a> is set to <a class="css" data-link-type="maybe"  id="ref-for-valdef-white-space-normal⑧">normal</a>, <a class="css" data-link-type="maybe"  id="ref-for-valdef-white-space-nowrap④">nowrap</a>, or <a class="css" data-link-type="maybe"  id="ref-for-valdef-white-space-pre-line③">pre-line</a>,
            the UA must <a data-link-type="dfn"  id="ref-for-hang②">hang</a> this sequence (unconditionally). 
      <li>
       If <a class="property" data-link-type="propdesc"  id="ref-for-propdef-white-space①⓪">white-space</a> is set to <a class="css" data-link-type="maybe"  id="ref-for-valdef-white-space-pre-wrap④">pre-wrap</a>,
             the UA must (unconditionally) <a data-link-type="dfn"  id="ref-for-hang③">hang</a> this sequence,
             unless the sequence is followed by a <a data-link-type="dfn"  id="ref-for-forced-line-break③">forced line break</a>,
             in which case it must <a data-link-type="dfn"  id="ref-for-conditionally-hang">conditionally hang</a> the sequence is instead.
             It may also visually collapse the character advance widths
             of any that would otherwise overflow. 
       <p class="note" role="note"><span>Note:</span> <a data-link-type="dfn"  id="ref-for-hang④">Hanging</a> the white space rather than collapsing it
             allows users to see the space when selecting or editing text.</p>
      <li>If <a class="property" data-link-type="propdesc"  id="ref-for-propdef-white-space①①">white-space</a> is set to <a class="css" data-link-type="maybe"  id="ref-for-valdef-white-space-break-spaces③">break-spaces</a>, <a data-link-type="dfn"  id="ref-for-hang⑤">hanging</a> or collapsing the advance width of the <a data-link-type="dfn"  id="ref-for-spaces②①">spaces</a>, <a data-link-type="dfn"  id="ref-for-tabs⑦">tabs</a>,
             or <a data-link-type="dfn"  id="ref-for-other-space-separators⑥">other space separators</a> at the end of the line is not allowed;
             those that overflow must <a data-link-type="dfn"  id="ref-for-wrapping②">wrap</a> to the next line. 
     </ul>
   </ol>
</blockquote>
</details>

<details>
<summary><b>Glossary</b></summary>

<table>
<tbody>
<tr>
  <td>
  inline
  </td>
  <td>
  An inline is an element inside of an inline formatting context.
  </td>
</tr>
<tr>
  <td>
  inline formatting context
  </td>
  <td>
  <a href="https://www.w3.org/TR/CSS2/visuren.html#inline-formatting"/>https://www.w3.org/TR/CSS2/visuren.html#inline-formatting</a>
  </td>
</tr>
<tr>
  <td>
  segment break
  </td>
  <td>
  <a href="https://www.w3.org/TR/2020/WD-css-text-3-20200429/#segment-break">https://www.w3.org/TR/2020/WD-css-text-3-20200429/#segment-break</a> 
  </td>
</tr>
<tr>
  <td>
  inter-element whitespace
  </td>
  <td>
  <a href="https://html.spec.whatwg.org/multipage//dom.html#inter-element-whitespace">https://html.spec.whatwg.org/multipage//dom.html#inter-element-whitespace</a>
  </td>
</tr>
</tbody>
</table>

</details>

But this reference considers multiple contexts that we can ignore in a minimal compatibility approach. The reference describes the required behavior for multiple values of the `white-space` CSS property, `normal`, `pre-line`, `nowrap`... We can keep focus in the `normal` value, since this is the default behavior reported by @fvsch. Also, bidirectional layouts for LTR can be considered later, because they add complexity and are limited by React Native own support of these features. Moreover, there seems to be other kind of subtleties depending on localization. Here are the highlights of the spec I have identified. :

- The rules are context-dependent: in inline formatting context for example, inter-element whitespaces must be collapsed, while they should to removed in block formatting contexts. This property makes a simple regex-based approach inefficient.
- A simplified run of the spec where assumed that the white-space rule is `white-space: normal;`:
  1. Any sequence of collapsible spaces and tabs immediately preceding or following a segment break (that is, any character causing a line break) is removed.
  2. Segment break transformation rules are applied: any collapsible segment break immediately following another collapsible segment break is removed. Then any remaining segment break is either transformed into a space or removed depending on the context before and after the break:
    - If the character immediately before or immediately after the segment break is the zero-width space character, then the break is removed, leaving behind the zero-width space.
    - Otherwise, if both the character before and after the segment break belong to the [space discarding character set](https://www.w3.org/TR/2020/WD-css-text-3-20200429/#space-discard-set), then the segment break is removed.
    - Otherwise, the segment break is converted to a space.
  3. Every collapsible tab is converted to a space.
  4. Any collapsible space immediately following another collapsible space&mdash;even one outside the boundary of the inline containing that space, provided both spaces are within the same inline formatting context&mdash;is collapsed.
- Because of the context-dependent quality of this algorithm, we will need to perform collapsing near rendering time instead of parsing. We could loosely map inline formatting context with instances of Text wrapper, and block formatting context with instances of Block wrapper. 


The W3C consortium also provides a gigantic test suite, and [one folder is specifically dedicated to CSS whitespaces](https://github.com/web-platform-tests/wpt/tree/master/css/css-text/white-space) which can be a source for inspiration. In the meantime, I have started to implement some basic tests regarding whitespaces, see 53b8679ddc74badb486348a7404fc835527cb7f4 and d76f99d9d44b3bb38fe92a7403b1165e6b10e765. A majority of them fail, of course, which is the point of this issue!

![2020-07-14-183415_352x100_scrot](https://user-images.githubusercontent.com/3646758/87478751-ab08c600-c600-11ea-9093-0e790d523ee8.png)

**Comment by brayanarrieta** [comment] 2020-11-09 21:46
> My current solution uses this module:
> https://gist.github.com/fvsch/d66282c34d48c86ec90bf5acbbff03f4
> 
> Which I’m using in alterData in this way:
> 
> ```js
> <HTML html={content} alterData={node => {
>   const newData = collapseText(node)
>   // return undefined to skip changing node text
>   return newData !== node.data ? newData : undefined
> }} />
> ```
> 
> Of course it cannot fix the two issues highlighted in the previous comment, but it does handle the leading whitespace and uncollapsed whitespace issues.

@fvsch what was the module that you use?

**Comment by jsamr** [comment] 2020-11-15 19:15
I am currently developing this behavior as part of a service for [Expensify](https://www.expensify.com/). The new engine following the whitespace RFC is being implemented here: https://github.com/native-html/core. An early release should be available in the upcoming week.

This pre-release will be part of the 6.x release cycle. If you are wondering why we're jumping from 4 to 6, the reason is that 6.x will require more recent versions of React Native, and we want all users to benefit from the 5.x enhancements already available in alpha. Also, the new engine changes the structure of nodes available with `onParsed`, and the `renderers` prop will probably look different.

**Comment by jsamr** [comment] 2020-11-16 22:13
I've made great progress with the new release! Given this snippet:

```html
<span>This is text!</span>





This is <strong>bold</strong> <em>italics</em>.
```

We now have:

<table>
<thead>
<tr>
<th><code>whiteSpace: pre;</code></th>
<th><code>whiteSpace: normal;</code></th>
</tr>
</thead>
<tbody>
<tr>
<td>


![Screenshot_1605564643](https://user-images.githubusercontent.com/3646758/99314193-7bccc480-283f-11eb-82fd-67e75bc210b0.png)

</td>
<td>

![Screenshot_1605564547](https://user-images.githubusercontent.com/3646758/99314179-766f7a00-283f-11eb-9902-bc2d33058473.png)

</td>
</tr>
</tbody>
</table>

You will be able to control the whitespace behavior with the special `whiteSpace`  style property in any of the places you could previously customize styles (baseFontStyles, tagsStyles ...etc).

**Comment by jsamr** [comment] 2020-11-27 14:11
<table>
<tr>
<td valign="top">

This issue has been fixed in the Foundry release. Try it out now! See #430 for instructions.

</td>
<td width="300">
<img width="300" src="https://user-images.githubusercontent.com/3646758/100457694-43c84b80-30a1-11eb-9124-7e870a88dd8a.png" />
</td>
</tr>
</table>

**Comment by thuongtv-vn** [comment] 2020-12-09 03:00
Hi @jsamr 
I could not apply "whiteSpace". I got this warning message:
```Failed prop type: Invalid props.style key 'whiteSpace' supplied to 'Text'``
Could you please tell me how can I apply it? Thanks

**Comment by jsamr** [comment] 2020-12-09 08:55
@thuongtv-vn Are you sure you're using the foundry pre-release? Best to continue the discussion on [our discord](https://discord.gg/dbEMMJM), the foundry thread (#430) or a separate issue, thank you !

**Comment by ahtisham09** [comment] 2020-12-16 11:13
solved this issue using following code:

```const filterQuestion = (q, curr) => {
    const tags = /(<\/?(?:img|br)[^>]*>)|<[^>]+>/gi;
    // const linebreaks = /(\r\n|\n|\r)/g;
    const tagSpaces = /\s/g;
    const subst = `$1`;
    let filteredQuestion = `<p>Q ${curr + 1}: ${q
      .replace(tags, subst)
      .replace(tagSpaces, ' ')}</p>`;

    console.log(filteredQuestion);

    return filteredQuestion;
  };```

might this would be helpful to eliminate the unwanted spaces and tags and just retain the desired tags you need in your html to render.

Jazak ALLAH

**Closed** 2021-06-08 01:16 UTC
Labels: domain:html, enhancement, is:help wanted

**Comment by aprilmintacpineda** [comment] 2021-06-21 06:59
You guys managed to make `text-decoration` work? https://github.com/meliorence/react-native-render-html/issues/495 can't make it work on mine.
