### ISSUE TITLE
Crash on android if get back on navigation with table

### ISSUE THREAD

**Issue by dzpt** [meliorence/react-native-render-html#483] opened 2021-05-11 15:17 UTC
### Oath

I swear that I have completed these tasks before submitting:

- [x] I have read the contribution guidelines here: https://git.io/JJ0Pg
- [x] I have read the documentation here: https://git.io/JJcAl 
- [x] I have confirmed that this bug has not been reported yet

### Decision table

- [x ] My issue does not look like “The HTML attribute 'xxx' is ignored” (unless
  we claim support for it),
- [ x] My issue does not look like “The HTML element `<yyy>` is not rendered”

##### React Native

```
System:
    OS: macOS 11.0.1
    CPU: (8) x64 Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz
    Memory: 24.70 MB / 8.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 12.18.3 - /usr/local/bin/node
    Yarn: Not Found
    npm: 6.14.6 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.9.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.2, DriverKit 20.0, macOS 11.0, tvOS 14.2, watchOS 7.1
    Android SDK:
      API Levels: 29, 30
      Build Tools: 28.0.3, 29.0.2, 30.0.3
      System Images: android-30 | Google APIs Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 4.1 AI-201.8743.12.41.7199119
    Xcode: 12.2/12B45b - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_282 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1
    react-native: 0.63.4 => 0.63.4
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

##### Libraries

- react-native-render-html: 5.1.0
- react-native-webview: 11.4.4
- react-native-screens: 3.2.0
- @react-navigation/stack@5.14.5
- @react-navigation/drawer@5.12.5
- @react-navigation/native@5.9.4

#### Devices

- Device 1 Xiaomi mi 8
  * OS: Android 10
  * Diagnostic: 
  * Environment: 

#### Reproduction

render html with given code `a<br/>a<br/>a<br/>a<br/>a<br/>a<br/>a<br/>a<br/>a<br/>a<br/>a<br/>a<br/>a<br/>a<br/>a<br/>a<br/>a<br/>a<br/>a<br/>a<br/>a<br/>a<br/>a<br/>a<br/>a<br/><table><tr><td>123123</td></tr></table>`
swipe left on react-navigation it will crash #393 

I've tried many ways like set opacity for table to 0.99 but it doesn't work (https://stackoverflow.com/questions/63171131/when-rendering-iframes-with-html-android-crashes-while-navigating-back-to-s/63171413#63171413)

the only way to work around is set `animationEnabled: false`

**Comment by dzpt** [comment] 2021-05-13 08:39
@jsamr hi, this is my repo.
https://github.com/dzpt/test-render-html
crash on android similator too.

**Comment by jsamr** [comment] 2021-05-13 12:32
@dzpt looking into it

**Comment by jsamr** [comment] 2021-05-13 16:58
@dzpt I could reproduce your issue without the need to involve react-native-render-html, see https://snack.expo.io/@jsamr/rnrh-webview-screens

I'll let this issue open and mark it as upstream-bug. When I'll find the time after releasing the beta of v6, I'll investigate workarounds again. Looks like a regression on `react-native-screens` part.

**Comment by veenedu** [comment] 2021-06-26 13:50
Any updates on this??

**Comment by jsamr** [comment] 2021-07-17 18:45
### I've reported the issue here: https://github.com/software-mansion/react-native-screens/issues/1015

Not much more I can do, hopefully it will be fixed upstream at some point.

### [In the meantime, you can check workarounds proposed in this StackOverflow post.](https://stackoverflow.com/a/63171413/2779871)

**Comment by amoiseenko-sc** [comment] 2021-08-05 14:24
This solution worked for me - https://github.com/react-native-webview/react-native-webview/issues/1161

You should hide WebView (or other heavy content) before navigate to another page

**Comment by jsamr** [comment] 2021-09-24 16:09
I am closing because this issue has to be fixed upstream and workarounds have been provided.

**Closed by jsamr** 2021-09-24 16:09 UTC
Labels: bug, bug:upstream
