### ISSUE TITLE
Update react-native to ^0.64.0 in peerDependencies

### ISSUE THREAD

**Issue by Ainias** [meliorence/react-native-render-html#508] opened 2021-07-19 13:17 UTC
### Oath

I swear that I have completed these tasks before submitting:

- [x] I have read the contribution guidelines here: https://git.io/JJ0Pg
- [x] I have read the documentation here: https://meliorence.github.io/react-native-render-html/
- [x] I have confirmed that this bug has not been reported yet

### Decision table

- [x] My issue does not look like “The HTML attribute 'xxx' is ignored” (unless
  we claim support for it),
- [x] My issue does not look like “The HTML element `<yyy>` is not rendered”

### Bug Report
When using react-native 0.64.x and react-native-render-html 6.0.2, `npm install` throws an error with unable to resolve dependency tree. When using `npm install --legacy-peer-deps` its working. 
In the package.json delivered in the release, react-native 0.64.0 is already defined as devDependency. Therefore it should be easy to update the peerDependency. 

#### Reproduction

1. create empty directory
2. create package.json with dependencies

> "dependencies": {
> 	"react-native":"^0.64.0",
> 	"react-native-render-html": "^6.0.2"  
>   }

3. run `npm install`

**Comment by jsamr** [comment] 2021-07-19 13:55
@Ainias Hey thank you for your report, good catch! That's probably due to how npm 7 works (I'm using 6.x locally); I'll fix that today.

**Comment by jsamr** [comment] 2021-07-19 18:34
@Ainias Thought I fixed in release 6.0.3. I added a CI step to avoid regressions, see https://github.com/meliorence/react-native-render-html/actions/runs/1046261556 but it failed again, investigation going on ...

**Comment by jsamr** [comment] 2021-07-19 19:04
@Ainias I think it's fixed in 6.0.4; could you try it out? CI still fails but it worked locally...

**Comment by jsamr** [comment] 2021-07-19 19:26
@Ainias Found out that it would fail with npm@7.7.6 but succeed with npm@7.20.0, because in the former, `*` in peerDependencies would be resolved __to the latest__ instead of __whichever__; which would conflict with `react-native` → `react` requirement. That was an npm bug!
See https://github.com/meliorence/react-native-render-html/runs/3107443720

Closing now, feel free to comment if you're still having issues.

**Closed by jsamr** 2021-07-19 19:26 UTC
Labels: bug
