### ISSUE TITLE
Custom Font Family being implement is not working correctly in Android but is working fine in IOS 

### ISSUE THREAD

**Issue by ThomasTeoSY** [meliorence/react-native-render-html#488] opened 2021-05-31 05:24 UTC
const DEFAULT_PROPS = {
      classesStyles: {
        "category-type": {
          fontSize: 15,
          color: appGlobal.COLOR_42,
          letterSpacing: 2,
          lineHeight: 30,
          fontFamily: "ProximaNova-Semibold"
        },
        "discount-percentage": {
          fontSize: 18,
          color: appGlobal.COLOR_42,
          fontFamily: "Trirong-Italic",
        },
      },
    };

var htmlRichText = `<span class="category-type">Testing 1<br /></span><span class="discount-percentage">Testing 2</span>`;

<HTML 
  {...DEFAULT_PROPS} 
  source={{ html: htmlRichText  }} 
/>
    
![image](https://user-images.githubusercontent.com/61544204/120143255-5bc88580-c212-11eb-8318-84ee5bab4038.png)
1s Image 

Issue: As shown in the 1st image, the text "Testing 2" did go in italic, and font family implementation seems to be working fine. However, the correct custom font family should look like as below 2nd image. (Kindly please refer to 2nd image in below). 
Please advise if whether I had missed out on any setting and anything more require from my side. Thanks in advance.

![image](https://user-images.githubusercontent.com/61544204/120143544-ddb8ae80-c212-11eb-9f61-128db0f69ee9.png)
2nd Image

**Comment by jsamr** [comment] 2021-05-31 13:42
Hi @ThomasTeoSY !
You are advised to follow [our guidelines](https://github.com/meliorence/react-native-render-html/blob/master/CONTRIBUTING.adoc#submitting-a-bug) to submit bug reports. Especially, we can't process reports which don't contain version information. If this issue happened in version 5.x, there is a good chance it has been fixed in the Foundry release, yet in alpha (see #430), which uses strict parsing of CSS properties. Feel free to update the report with version information, and we will be able to process it.

**Comment by ThomasTeoSY** [comment] 2021-06-02 04:09
Hi @jsamr thank you so much the for quick response. The version I am using currently is 5.x as show in below. 

"react-native-render-html": "^5.1.0",

**Comment by jsamr** [comment] 2021-06-02 10:12
@ThomasTeoSY It's hard to tell without a reproduction. How do you load those fonts?  Can you confirm you have been able to use this font on Android, without RNRH?

**Comment by ThomasTeoSY** [comment] 2021-06-03 03:18
Hi @jsamr , yes, I can confirm the font is being implemented correctly in android. In my first comment, the 2nd image I am showing is using normal <Text> component with style, without RNRH.

**Comment by jsamr** [comment] 2021-06-03 10:21
@ThomasTeoSY The only place in the v5 source space where `fontFamily` is referred to, is in this whitelist of supported styles for text blocks:
https://github.com/meliorence/react-native-render-html/blob/819e06e175b8fa664724bec9519bb50f2da33bec/src/HTMLUtils.js#L258

And for the `pre` tag, where `fontFamily| is forced to mono.

https://github.com/meliorence/react-native-render-html/blob/819e06e175b8fa664724bec9519bb50f2da33bec/src/HTMLRenderers.js#L187

There is no distinct behaviors implemented for styles between iOS and Android in react-native-render-html v5 other then that `pre` exception.

For this very reason, the fact that your issue was not reproducible on iOS is a good indication that it likely comes either from your setup, or from platform inconsistent behaviors in React Native (there are many!). As you have not provided a full reproduction, I am unfortunately unable to investigate further. If you are willing to share one, I'll be happy to take a look.

Best,

JSR

**Comment by jsamr** [comment] 2021-06-08 18:33
I am closing because a reproduction was not provided and I can't do much with the actual report. But I'm open to reopening if a reproduction is provided, thanks!

**Closed by jsamr** 2021-06-08 18:33 UTC
Labels: bug, is:missing reproduction, is:missing template, is:waiting for feedback

**Comment by jsamr** [comment] 2021-12-06 16:35
For anyone stumbling on this, you should not use postscript fonts, rather use XML fonts and refer to the font name by font family, e.g. `Tirong`. See https://stackoverflow.com/a/70247374/2779871

**Comment by Navipro70** [comment] 2022-02-07 13:18
@jsamr 
Maybe not related to this issue, but tag <i><i/> set font-style: 'italic' to text, but to make font italic on android correctly, we should use font-family: 'FONT-NAME-ITALIC' for android
